In [619]:
import numpy as np

In [620]:
V = np.zeros((6, 12))

In [621]:
V[1,11]=-1
V[0,11] = 1
gamma = 0.9
epsilon = 0.2
Phi = 0.8

In [622]:
V.shape

(6, 12)

In [623]:
V

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [624]:
def find_move(x,y, shape_v):
  up = (x-1, y)
  down = (x+1, y)
  left = (x, y-1)
  right = (x, y+1)

  moves = [up, down, left, right]
  
  list_move = []
  for move in moves:
    for i, elem in enumerate(move):
      if elem < 0:
        break
      elif elem >= shape_v[i]:
        break
      if i:
        list_move.append(move)
  return list_move

In [625]:
block = [
(0, 4), (0, 8), 
(1, 4), (1, 6), (1, 8), 
(2, 1), (2, 2), (2, 4), (2, 6), (2, 8),
(3, 1), (3, 6), (3, 8),
(4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 8), (4, 9),
(5, 4)
]
len(block)

22

In [626]:
results = []
for x in range(len(V)):
  for y in range(len(V[0])):
    if (x, y) in block:
      continue
    list_move = find_move(x, y, V.shape)
    for move in list_move:
      for block_move in block:
        if move == block_move:
          list_move.remove(move)
    dict_move = {"cell": (x, y), "moves": list_move}
    results.append(dict_move)

In [627]:
for blockCell in block:
    V[blockCell[0]][blockCell[1]] = -100

In [628]:
V

array([[   0.,    0.,    0.,    0., -100.,    0.,    0.,    0., -100.,
           0.,    0.,    1.],
       [   0.,    0.,    0.,    0., -100.,    0., -100.,    0., -100.,
           0.,    0.,   -1.],
       [   0., -100., -100.,    0., -100.,    0., -100.,    0., -100.,
           0.,    0.,    0.],
       [   0., -100.,    0.,    0.,    0.,    0., -100.,    0., -100.,
           0.,    0.,    0.],
       [   0., -100., -100., -100., -100., -100., -100.,    0., -100.,
        -100.,    0.,    0.],
       [   0.,    0.,    0.,    0., -100.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.]])

In [629]:
results

[{'cell': (0, 0), 'moves': [(1, 0), (0, 1)]},
 {'cell': (0, 1), 'moves': [(1, 1), (0, 0), (0, 2)]},
 {'cell': (0, 2), 'moves': [(1, 2), (0, 1), (0, 3)]},
 {'cell': (0, 3), 'moves': [(1, 3), (0, 2)]},
 {'cell': (0, 5), 'moves': [(1, 5), (0, 6)]},
 {'cell': (0, 6), 'moves': [(0, 5), (0, 7)]},
 {'cell': (0, 7), 'moves': [(1, 7), (0, 6)]},
 {'cell': (0, 9), 'moves': [(1, 9), (0, 10)]},
 {'cell': (0, 10), 'moves': [(1, 10), (0, 9), (0, 11)]},
 {'cell': (0, 11), 'moves': [(1, 11), (0, 10)]},
 {'cell': (1, 0), 'moves': [(0, 0), (2, 0), (1, 1)]},
 {'cell': (1, 1), 'moves': [(0, 1), (1, 0), (1, 2)]},
 {'cell': (1, 2), 'moves': [(0, 2), (1, 1), (1, 3)]},
 {'cell': (1, 3), 'moves': [(0, 3), (2, 3), (1, 2)]},
 {'cell': (1, 5), 'moves': [(0, 5), (2, 5), (1, 6)]},
 {'cell': (1, 7), 'moves': [(0, 7), (2, 7), (1, 8)]},
 {'cell': (1, 9), 'moves': [(0, 9), (2, 9), (1, 10)]},
 {'cell': (1, 10), 'moves': [(0, 10), (2, 10), (1, 9), (1, 11)]},
 {'cell': (1, 11), 'moves': [(0, 11), (2, 11), (1, 10)]},
 {'cel

In [630]:
def cal_cell_val(x, y, dict_move):
    for move in dict_move:
        if move["cell"] == (x , y):
            move_list = move["moves"]
            break
    value_range = []
    for i in range(len(move_list)):
        marked = move_list[i]
        sum = 0
        for j in move_list:
            if j == marked:
                sum += Phi * (0.0+gamma*V[marked])
            else:
                sum += epsilon/(len(move_list)-1)*(0.0+gamma*V[j])
        value_range.append(sum)
    return max(value_range)

In [631]:
cal_cell_val(0, 10, results)


0.7200000000000001

In [632]:
V

array([[   0.,    0.,    0.,    0., -100.,    0.,    0.,    0., -100.,
           0.,    0.,    1.],
       [   0.,    0.,    0.,    0., -100.,    0., -100.,    0., -100.,
           0.,    0.,   -1.],
       [   0., -100., -100.,    0., -100.,    0., -100.,    0., -100.,
           0.,    0.,    0.],
       [   0., -100.,    0.,    0.,    0.,    0., -100.,    0., -100.,
           0.,    0.,    0.],
       [   0., -100., -100., -100., -100., -100., -100.,    0., -100.,
        -100.,    0.,    0.],
       [   0.,    0.,    0.,    0., -100.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.]])

In [633]:
for count in range(50):
    for i in range(len(V)):
        for j in range(len(V[0])):
            check = False
            if ((i, j) in block):
                check = True
            if check == False: 
                V[i][j] = cal_cell_val(x, y , results)
             

In [634]:
V

array([[   0.,    0.,    0.,    0., -100.,    0.,    0.,    0., -100.,
           0.,    0.,    0.],
       [   0.,    0.,    0.,    0., -100.,    0., -100.,    0., -100.,
           0.,    0.,    0.],
       [   0., -100., -100.,    0., -100.,    0., -100.,    0., -100.,
           0.,    0.,    0.],
       [   0., -100.,    0.,    0.,    0.,    0., -100.,    0., -100.,
           0.,    0.,    0.],
       [   0., -100., -100., -100., -100., -100., -100.,    0., -100.,
        -100.,    0.,    0.],
       [   0.,    0.,    0.,    0., -100.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.]])