In [59]:
import random
import numpy as np

def gen_list(length):
  return [random.randint(0, 1) for _ in range(length)]

def main():
    randomList = np.zeros(10)
    print(f"Fill: {randomList}")
    numSafe = list(randomList).count(0)
    print(numSafe)
    step = 0
    way = []
    while step < numSafe:
      checkList = randomList
      while True:
          position = random.randint(0, len(checkList) - 1)
          if checkList[position] == 1:
              print(f"Bước {step} không hợp lệ, vị trí {position + 1} đã có giá tri")
              break
          checkList[position] = 1
          print(f"Bước {step} hợp lệ, vị trí điền vào là {position + 1}, list sau bước {step}:\n {checkList}")
          way.append(position + 1)
          step += 1
    print("Thứ tự các bước có thể giải quyết là: ", way)

if __name__ == "__main__":
  main()

Fill: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10
Bước 0 hợp lệ, vị trí điền vào là 1, list sau bước 0:
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Bước 1 hợp lệ, vị trí điền vào là 4, list sau bước 1:
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Bước 2 không hợp lệ, vị trí 1 đã có giá tri
Bước 2 hợp lệ, vị trí điền vào là 5, list sau bước 2:
 [1. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
Bước 3 hợp lệ, vị trí điền vào là 9, list sau bước 3:
 [1. 0. 0. 1. 1. 0. 0. 0. 1. 0.]
Bước 4 không hợp lệ, vị trí 9 đã có giá tri
Bước 4 hợp lệ, vị trí điền vào là 8, list sau bước 4:
 [1. 0. 0. 1. 1. 0. 0. 1. 1. 0.]
Bước 5 không hợp lệ, vị trí 5 đã có giá tri
Bước 5 hợp lệ, vị trí điền vào là 6, list sau bước 5:
 [1. 0. 0. 1. 1. 1. 0. 1. 1. 0.]
Bước 6 không hợp lệ, vị trí 6 đã có giá tri
Bước 6 hợp lệ, vị trí điền vào là 3, list sau bước 6:
 [1. 0. 1. 1. 1. 1. 0. 1. 1. 0.]
Bước 7 không hợp lệ, vị trí 5 đã có giá tri
Bước 7 không hợp lệ, vị trí 1 đã có giá tri
Bước 7 không hợp lệ, vị trí 8 đã có giá tri
Bước 7 không hợp lệ, vị trí 1 đã có giá tr